[book]
authors = ["leepl37"]
language = "en"
multilingual = false
src = "src"
title = "러스트 언어에 대한 지식 공유방"



[output.html.playpen]
editable = true
editor = "ace"
line-number = true

[output.html.fold]
enable = true 

[rust]
edition = "2021"
