[book]
src = "src"
title = "러스트 언어에 대한 지식 공유방"
description = "rust by example 공식 홈페이지 번역 & 내 입맛에 맞게 주석" 
author = "tony_lee"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true

[rust]
edition = "2021"
